Repository vbr-calc/vbr, pull requests merged in 2024-07, with the labels that each got.

#114 add analytical andrade model
  Projects/vbr_core_examples/CB_015_analytical_andrade.m
  Projects/vbr_core_examples/CB_016_complex_viscosity.m
  docs/_pages/examples/CB_011_meltEffects.md
  docs/_pages/examples/CB_015_analytical_andrade.md
  docs/_pages/examples/CB_016_complex_viscosity.md
  docs/_pages/examples/vbrcore.md
  docs/_pages/gettingstarted/methods.md
  docs/_pages/vbrmethods/anel/andradeanalytical.md
  docs/_pages/vbrmethods/anelastic.md
  docs/assets/images/CBs/CB_015_analytical_andrade.png
  docs/assets/images/CBs/CB_016_complex_viscosity.png
  vbr/testing/test_vbrcore_011_analytical_andrade.m
  vbr/vbrCore/functions/Q_andrade_analytical.m
  vbr/vbrCore/functions/checkInput.m
  vbr/vbrCore/params/Params_Anelastic.m
Labels: enhancement

#117 fix Andrade model docs typo
  docs/_pages/vbrmethods/anelastic.md
Labels: documentation

#118 fix analytical andrade
  Projects/vbr_core_examples/CB_015_analytical_andrade.m
  Projects/vbr_core_examples/CB_016_complex_viscosity.m
  docs/_pages/examples/CB_011_meltEffects.md
  docs/_pages/examples/CB_015_analytical_andrade.md
  docs/_pages/examples/CB_016_complex_viscosity.md
  docs/assets/images/CBs/CB_001_0D_scalar.png
  docs/assets/images/CBs/CB_015_analytical_andrade.png
  docs/assets/images/CBs/CB_016_complex_viscosity.png
  vbr/support/buildingdocs/README.md
  vbr/support/buildingdocs/buildExampleDocs.py
  vbr/vbrCore/functions/Q_andrade_analytical.m
Labels: bug, documentation

#125 fix typo in docstring of test for analytical_andrade
  vbr/testing/test_vbrcore_011_analytical_andrade.m
  vbr/vbrCore/functions/Q_andrade_analytical.m
Labels: ci_and_testing

#126 fixed the devguide markdown issue
  docs/_pages/contrib/devguide.md
Labels: bug, documentation

#128 Deleted unused line in Q_xfit_mxw.
  vbr/vbrCore/functions/Q_xfit_mxw.m
Labels: enhancement

#122 vbrListMethods bug fix for matlab compatibility
  vbr/support/vbrListMethods.m
Labels: bug
